### ISSUE TITLE
HL7 MESSAGE

### ISSUE THREAD

**Issue by Gehlot** [dib0/HL7Fuse#5]
I WANT TO pass message and get ack with the help of bellowing code so what do i write in this ExecuteCommand class. 

namespace TestApplication.V24
{
public class MessageFactory : ICommand<MLLPSession, HL7RequestInfo>
{
# region Public properties

public virtual string Name
{
get { return "My implementation name"; }
}
# endregion
# region Public methods

public void ExecuteCommand(MLLPSession session, HL7RequestInfo requestInfo)
{
// Do something with the HL7 message
// requestInfo.Message
}
# endregion

}
}

**Comment by dib0** [comment]
Hi!

Yes. Well almost. The factory class must inherit the right ICommand: : ICommand<MLLPSession, HL7RequestInfo>

Your namespace suggests that you want a factory for V24 specifically. Note that in that case you only are able to support 1 version. If you want support for more that one HL7 version the Factory receives the messages and then do version specific handling.

**Comment by Gehlot** [comment]
Hello
 i will use HL7Fuse in my project 
and i will use inherit the right ICommand: : ICommand and pass a HL7 message where i got a result 
but in last goes in catch and show a error 
![2015-04-16_112045](https://cloud.githubusercontent.com/assets/7369177/7174801/ab078b40-e42a-11e4-856a-b371170369c5.png)
Please give any suggestion for solve this issue and i am also trying to solve this issue

**Comment by dib0** [comment]
Hi,

Based on this information it is quite hard for me to tell what the problem is. Is the string message filled with the right message?

Before that, the GetAck method probably returned an empty message. This method relies on the NHapi assemblies. Are all NHapi Assemblies in the \bin\Debug directory (or the startup directory)?

**Comment by Gehlot** [comment]
ok
i am using regarding you NHapiTools class

 Message = "MSH|^~\&|EPIC|EPICADT|SMS|SMSADT|199912271408|CHARRIS|ADT^A04^ADT_A01|1817457|D|2.5|PID||0493575^^^2^ID 1|454721||DOE^JOHN^^^^|DOE^JOHN^^^^|19480203|M||B|254 MYSTREET AVE^^MYTOWN^OH^44123^USA||(216)123-4567|||M|NON|400003403~1129086|NK1||ROE^MARIE^^^^|SPO||(216)123-4567||EC|||||||||||||||||||||||||||PV1||O|168~219^^^^^^^^^||||277^ALLEN MYLASTNAME^BONNIE^^^^|||||||||| ||2688684|||||||||||||||||||||||||199912271408||||||002376853";
            PipeParser parser = new PipeParser();
            IMessage m = parser.Parse(Message);
            //hl7requestInfo.Message = m;
            SimpleMLLPClient client = new SimpleMLLPClient("127.0.0.1", 6060);
            client.SendHL7Message(Message);

but no reply , my code hang on loop

**Comment by dib0** [comment]
Yes, I understand. Since HL7Fuse breaks, you won't get a reply.

I was talking about the code in HL7Fuse. In your screenshot you see the method Send(HL7RequestInfo)

The next line in that method is GetAck(HL7RequestInfo). My guess is that the HL7RequestInfo.Message property is empty. And because it is, the ACK message can't be created.
If this property is not empty and filled with the right message, the problem can be that the NHapi assemblies (besides the NHapiTools assemblies) aren't in the executing directory.

If the NHapi assemblies aren't there, the ACK message creation can't be done, since the version specific class is in these assemblies.
So please, copy all the NHapiTools and NHapi assemblies to the execuring directory (..\bin\Debug) an I think this problem will be solved.
